-- ================================================================
-- E-COMMERCE CUSTOMER ANALYTICS & RFM SEGMENTATION
-- Project: Analyze 60,000+ transactions to segment 15,000 customers
-- Goal: Identify high-value customers and retention opportunities
-- ================================================================

USE ecommerce_analytics;

-- ================================================================
-- SECTION 1: DATA EXPLORATION
-- Quick checks to understand the data structure and date range
-- ================================================================

-- View available tables
SHOW TABLES;

-- Check date range of orders (helps set RFM analysis date)
SELECT 
    MIN(order_date) as earliest_order, 
    MAX(order_date) as latest_order 
FROM orders;

-- Preview sample data from each table
SELECT * FROM customers LIMIT 5;
SELECT * FROM orders LIMIT 5;
SELECT * FROM order_items LIMIT 5;
SELECT * FROM products LIMIT 5;


-- ================================================================
-- SECTION 2: RFM METRICS CALCULATION
-- Calculate Recency, Frequency, and Monetary value for each customer
-- ================================================================

CREATE OR REPLACE VIEW customer_rfm_metrics AS
SELECT 
    c.customer_id,
    c.location,
    c.age_group,
    
    -- RECENCY: Days since last purchase (as of May 31, 2025)
    DATEDIFF('2025-05-31', MAX(o.order_date)) as recency_days,
    
    -- FREQUENCY: Total number of orders placed
    COUNT(DISTINCT o.order_id) as frequency,
    
    -- MONETARY: Total revenue generated by customer
    ROUND(SUM(oi.quantity * oi.unit_price), 2) as monetary_value,
    
    -- Additional useful metrics
    MIN(o.order_date) as first_purchase_date,
    MAX(o.order_date) as last_purchase_date,
    ROUND(AVG(oi.quantity * oi.unit_price), 2) as avg_order_value
    
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
LEFT JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.location, c.age_group;


-- ================================================================
-- SECTION 3: RFM SCORING
-- Convert raw metrics into 1-5 scores for segmentation
-- ================================================================

CREATE OR REPLACE VIEW customer_rfm_scores AS
SELECT 
    *,
    
    -- RECENCY SCORE: Lower days = More recent = Higher score
    CASE 
        WHEN recency_days <= 30 THEN 5   -- Purchased within last month
        WHEN recency_days <= 60 THEN 4   -- Purchased within 2 months
        WHEN recency_days <= 90 THEN 3   -- Purchased within 3 months
        WHEN recency_days <= 180 THEN 2  -- Purchased within 6 months
        ELSE 1                            -- No purchase in 6+ months
    END as recency_score,
    
    -- FREQUENCY SCORE: More orders = Higher score
    CASE 
        WHEN frequency >= 10 THEN 5      -- 10+ orders (power users)
        WHEN frequency >= 7 THEN 4       -- 7-9 orders
        WHEN frequency >= 4 THEN 3       -- 4-6 orders
        WHEN frequency >= 2 THEN 2       -- 2-3 orders
        ELSE 1                            -- Only 1 order
    END as frequency_score,
    
    -- MONETARY SCORE: Higher spending = Higher score
    CASE 
        WHEN monetary_value >= 1000 THEN 5  -- $1000+ (VIP customers)
        WHEN monetary_value >= 500 THEN 4   -- $500-999
        WHEN monetary_value >= 250 THEN 3   -- $250-499
        WHEN monetary_value >= 100 THEN 2   -- $100-249
        ELSE 1                               -- Under $100
    END as monetary_score
    
FROM customer_rfm_metrics;


-- ================================================================
-- SECTION 4: CUSTOMER SEGMENTATION
-- Classify customers into 7 strategic segments based on RFM scores
-- ================================================================

CREATE OR REPLACE VIEW customer_segments AS
SELECT 
    *,
    CASE 
        -- Champions: Best customers (high R, F, M)
        WHEN recency_score >= 4 AND frequency_score >= 4 AND monetary_score >= 4 
            THEN 'Champions'
        
        -- Loyal: Frequent buyers with good spend
        WHEN frequency_score >= 4 AND monetary_score >= 3 
            THEN 'Loyal'
        
        -- Big Spenders: High value but not frequent
        WHEN monetary_score >= 4 
            THEN 'Big Spenders'
        
        -- At Risk: Used to be good customers but haven't purchased recently
        WHEN recency_score <= 2 AND frequency_score >= 3 
            THEN 'At Risk'
        
        -- Promising: Recent customers with potential
        WHEN recency_score >= 4 AND frequency_score <= 2 
            THEN 'Promising'
        
        -- Need Attention: Moderate customers losing engagement
        WHEN recency_score = 3 AND frequency_score <= 3 
            THEN 'Need Attention'
        
        -- Lost: Inactive customers
        ELSE 'Lost'
    END as customer_segment
    
FROM customer_rfm_scores;


-- ================================================================
-- SECTION 5: KEY BUSINESS INSIGHTS
-- Critical queries that drive business decisions
-- ================================================================

-- INSIGHT 1: Segment Overview - Where is the revenue?
-- Shows: Champions drive 61% of revenue with just 17% of customers
SELECT 
    customer_segment,
    COUNT(*) as customer_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customer_segments), 2) as pct_of_customers,
    CONCAT('$', FORMAT(ROUND(SUM(monetary_value), 0), 0)) as total_revenue,
    ROUND(SUM(monetary_value) * 100.0 / (SELECT SUM(monetary_value) FROM customer_segments), 2) as pct_of_revenue,
    CONCAT('$', FORMAT(ROUND(AVG(monetary_value), 0), 0)) as avg_customer_value,
    ROUND(AVG(frequency), 1) as avg_orders,
    ROUND(AVG(recency_days), 0) as avg_days_since_purchase
FROM customer_segments
GROUP BY customer_segment
ORDER BY SUM(monetary_value) DESC;


-- INSIGHT 2: At-Risk Customer Opportunity
-- Shows: 850 high-value customers at churn risk = $380K recovery opportunity
SELECT 
    COUNT(*) as high_value_at_risk_count,
    CONCAT('$', FORMAT(ROUND(SUM(monetary_value), 0), 0)) as total_recovery_opportunity
FROM customer_segments
WHERE monetary_value >= 500 
  AND recency_days >= 90;


-- INSIGHT 3: Top At-Risk Customers (Action List)
-- These are your immediate retention targets
SELECT 
    customer_id,
    location,
    age_group,
    customer_segment,
    CONCAT('$', FORMAT(ROUND(monetary_value, 0), 0)) as lifetime_value,
    frequency as total_orders,
    recency_days as days_since_purchase,
    last_purchase_date
FROM customer_segments
WHERE monetary_value >= 500 
  AND recency_days >= 90
ORDER BY monetary_value DESC
LIMIT 20;


-- INSIGHT 4: Overall Business Summary
-- Total customers, segments, and revenue
SELECT 
    COUNT(*) as total_customers,
    COUNT(DISTINCT customer_segment) as total_segments,
    CONCAT('$', FORMAT(ROUND(SUM(monetary_value), 0), 0)) as total_revenue,
    CONCAT('$', FORMAT(ROUND(AVG(monetary_value), 0), 0)) as avg_customer_value
FROM customer_segments;


-- ================================================================
-- END OF ANALYSIS
-- Key Findings:
-- • 15,000 customers analyzed across $9.2M in revenue
-- • Top 17% Champions generate 61% of revenue ($5.6M)
-- • 850 at-risk customers represent $380K recovery opportunity
-- ================================================================
